swagger: "2.0"
info:
  description: idk
  version: "19.11.0"
  title: TravelStorms Main API Gateway
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/ts-main"

# Paths supported by the server application
paths:
  /address/autocomplete/{addr}:
    get:
      operationId: "address.autocomplete"
      tags:
        - "Address"
      summary: "The people data structure supported by the server applicatio"
      description: "Read the list of people"
      parameters:
        - name: addr
          in: path
          description: address to autocomplete
          type: string
          required: True
      responses:
        200:
          description: "Successful read people list operation"

  /route/{start_addr}/{end_addr}:
    get:
      operationId: "route.buildRoute"
      tags:
        - "Address"
      summary: "The people data structure supported by the server applicatio"
      description: "Read the list of people"
      parameters:
        - name: start_addr
          in: path
          description: Starting Address
          type: string
          required: True
        - name: end_addr
          in: path
          description: Destination Address
          type: string
          required: True
      responses:
        200:
          description: "Successful read people list operation"
